language: php

php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5.9

branches:
  except:
    - gh-pages

install:
  - composer install

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - ./vendor/bin/codecept build

after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - ./vendor/bin/codecept run --coverage --coverage-xml --coverage-html